# Generated by Django 3.2.16 on 2022-12-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpayment',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
